// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzhhnedeujqijyynpazv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6aGhuZWRldWpxaWp5eW5wYXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDA0NjcsImV4cCI6MjA2OTc3NjQ2N30.0Q0Pbx1_YUW2WCPVMs22N9RPlsb-1y5xlsihf1oDCMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});