// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtzskzqwcisuweemzmyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0enNrenF3Y2lzdXdlZW16bXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzI3ODQsImV4cCI6MjA2OTk0ODc4NH0.aDWHfEJPRaAtOclOUDUnLL6QrVOV8Y_lpBzbBoKqcwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});